/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const MdiAccountCowboyHat: typeof import('~icons/mdi/account-cowboy-hat')['default']
  const MdiAlarm: typeof import('~icons/mdi/alarm')['default']
  const MdiCircleHalfFull: typeof import('~icons/mdi/circle-half-full')['default']
  const MdiFileHidden: typeof import('~icons/mdi/file-hidden')['default']
  const MdiFileRemove: typeof import('~icons/mdi/file-remove')['default']
  const MdiFileRestore: typeof import('~icons/mdi/file-restore')['default']
  const MdiLightbulbOn: typeof import('~icons/mdi/lightbulb-on')['default']
  const MdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
  const computed: typeof import('vue')['computed']
  const ref: typeof import('vue')['ref']
}
